#!/bin/bash -x
set -e

echo "Reviewing pull-request $1"

PID=$(lsof -t -i :4000 || true)

if [ -n "$PID" ]; then
  echo "killing previous server instance $PID"
  kill $PID || true
fi

cd ~/Projects/
#git clone git@github.com:ManageIQ/manageiq.git -o upstream manageiq-review
cd manageiq-review

echo 'Preparing ManageIQ master'

git reset --hard
git checkout master

for remote in $(git remote | grep -v upstream); do git remote rm $remote; done
for branch in $(git branch -l | grep pull); do git branch -D $branch; done

git pull upstream

cp ~/Projects/templates/database.yml config/
echo 10 > REGION
cp certs/v2_key.dev certs/v2_key
bundle install

echo 'Migrating database'
bundle exec rake db:migrate

echo 'Fetching pull request'
~/bin/github-fetch-pullrequest $1

echo "Launching..."
nohup bundle exec rails s -b 0.0.0.0 -p 4000 &

while true; do
  sleep 10
  lsof -i :4000 && break
done

#xdg-open http://localhost:4000
google-chrome-stable http://localhost:4000 https://github.com/ManageIQ/manageiq/pull/$1

# memcached -l 0.0.0.0:11111 -d

echo "Done"
